const input = document.querySelector('input')
const ekamtahark = document.getElementById('Ekamtahark')
const clear = document.getElementById('clear')
const soch = document.getElementById('Sochvjar')
const luys = document.getElementById('luys')
const jur = document.getElementById('jur')
const gas = document.getElementById('gas')
const inta = document.getElementById('inta')
const trash = document.getElementById('trash')
const tax = document.getElementById('tax')
const phone = document.getElementById('phone')
const fee = document.getElementById('fee')
const Tax = document.getElementById('Tax')
const vat = document.getElementById('vat')
const cable = document.getElementById('cable')
const tax2 = document.getElementById('Tax2')
const fe = document.getElementById('fe')
const main = document.getElementById('main')
const el = document.getElementById('el')


input.addEventListener('keyup' , () => {
    let val = input.value
    let clearNum = 0
    if(val >= 100000 && val > 500000){
        clearNum = clearNum + Math.floor(val * 20 / 100)
        clearNum = clearNum + Math.floor(val * 2 / 100)
        clearNum = clearNum + Math.floor(val * 2 / 100)
        clearNum = clearNum + Math.floor(val * 5 / 100)
        clearNum = clearNum + Math.floor(val * 4 / 100)
        clearNum = clearNum + Math.floor(val * 10 / 100)
        clearNum = clearNum + Math.floor(val * 7 / 100)
        clearNum = clearNum + Math.floor(Math.random() * 30000)
        clearNum = clearNum + Math.floor(Math.random() * 30000)
        clearNum = clearNum + Math.floor(Math.random() * 30000)
        clearNum = clearNum + Math.floor(Math.random() * 30000)
        clearNum = clearNum + Math.floor(Math.random() * 30000)
        clearNum = clearNum + Math.floor(Math.random() * 30000)
        clearNum = clearNum + Math.floor(Math.random() * 30000)
        clearNum = clearNum + Math.floor(Math.random() * 30000)
        clearNum = clearNum + Math.floor(Math.random() * 30000)
        clearNum = clearNum + Math.floor(Math.random() * 30000)
        

        // clearNum = clearNum + Math.floor(val * 3 / 100)
        // clearNum = clearNum + Math.floor(val * 1.5 / 100)
        // clearNum = clearNum + Math.floor(val * 5 / 100)
        // clearNum = clearNum + Math.floor(val * 3 / 100)
        // clearNum = clearNum + Math.floor(val * 2 / 100)
        clearNum = clearNum + 1000
        ekamtahark.innerText = `${Math.floor(val * (20 / 100))} Amd`
        soch.innerText = `${Math.floor(val * (2 / 100))} Amd`
        fe.innerText = `${Math.floor(val * (2 / 100))} Amd`
        tax.innerText = `${Math.floor(val * (5 / 100))} Amd`
        tax2.innerText = `${Math.floor(val * (4 / 100))} Amd`
        Tax.innerText = `${Math.floor(val * (10 / 100))} Amd`
        vat.innerText = `${Math.floor(val * (7 / 100))} Amd`
        luys.innerText = Math.floor((Math.random() * 30000))
        jur.innerText = Math.floor(Math.random() *  30000)
        gas.innerText = Math.floor(Math.random() *  30000)
        inta.innerText = Math.floor(Math.random() * 30000)
        trash.innerText = Math.floor( Math.random() *30000)
        phone.innerText = Math.floor( Math.random() *30000)
        fee.innerText = Math.floor( Math.random() *30000)
        cable.innerText = Math.floor( Math.random() *30000)
        main.innerText = Math.floor( Math.random() *30000)
        el.innerText = Math.floor( Math.random() *30000)
        clear.innerText = val - clearNum
    } else if(val >= 500000 && val > 1000000){
        clearNum = clearNum + Math.floor(val * 25 / 100)
        clearNum = clearNum + Math.floor(val * 5 / 100)
        clearNum = clearNum + Math.floor(val * 5 / 100)
        clearNum = clearNum + Math.floor(val * 8 / 100)
        clearNum = clearNum + Math.floor(val * 7 / 100)
        clearNum = clearNum + Math.floor(val * 13 / 100)
        clearNum = clearNum + Math.floor(val * 10 / 100)
        clearNum = clearNum + Math.floor(Math.random() * 50000)
        clearNum = clearNum + Math.floor(Math.random() * 50000)
        clearNum = clearNum + Math.floor(Math.random() * 50000)
        clearNum = clearNum + Math.floor(Math.random() * 50000)
        clearNum = clearNum + Math.floor(Math.random() * 50000)
        clearNum = clearNum + Math.floor(Math.random() * 50000)
        clearNum = clearNum + Math.floor(Math.random() * 50000)
        clearNum = clearNum + Math.floor(Math.random() * 50000)
        clearNum = clearNum + Math.floor(Math.random() * 50000)
        clearNum = clearNum + Math.floor(Math.random() * 50000)
        clearNum = clearNum + 1000
        ekamtahark.innerText = `${Math.floor(val * (25 / 100))} Amd`
        soch.innerText = `${Math.floor(val * (5 / 100))} Amd`
        fe.innerText = `${Math.floor(val * (5 / 100))} Amd`
        tax.innerText = `${Math.floor(val * (8 / 100))} Amd`
        tax2.innerText = `${Math.floor(val * (7 / 100))} Amd`
        Tax.innerText = `${Math.floor(val * (13 / 100))} Amd`
        vat.innerText = `${Math.floor(val * (10 / 100))} Amd`
        luys.innerText = Math.floor((Math.random() * 50000))
        jur.innerText = Math.floor(Math.random() * 50000)
        gas.innerText = Math.floor(Math.random() * 50000)
        inta.innerText = Math.floor(Math.random() * 50000)
        trash.innerText = Math.floor( Math.random() * 50000)
        phone.innerText = Math.floor( Math.random() * 50000)
        fee.innerText = Math.floor( Math.random() * 50000)
        cable.innerText = Math.floor( Math.random() * 50000)
        main.innerText = Math.floor( Math.random() * 50000)
        el.innerText = Math.floor( Math.random() * 50000)
        clear.innerText = val - clearNum
} else if (val >= 1000000){
        clearNum = clearNum + Math.floor(val * 30 / 100)
        clearNum = clearNum + Math.floor(val * 10 / 100)
        clearNum = clearNum + Math.floor(val * 10 / 100)
        clearNum = clearNum + Math.floor(val * 13 / 100)
        clearNum = clearNum + Math.floor(val * 12 / 100)
        clearNum = clearNum + Math.floor(val * 17 / 100)
        clearNum = clearNum + Math.floor(val * 15 / 100)
        clearNum = clearNum + Math.floor(Math.random() * 60000)
        clearNum = clearNum + Math.floor(Math.random() * 60000)
        clearNum = clearNum + Math.floor(Math.random() * 60000)
        clearNum = clearNum + Math.floor(Math.random() * 60000)
        clearNum = clearNum + Math.floor(Math.random() * 60000)
        clearNum = clearNum + Math.floor(Math.random() * 60000)
        clearNum = clearNum + Math.floor(Math.random() * 60000)
        clearNum = clearNum + Math.floor(Math.random() * 60000)
        clearNum = clearNum + Math.floor(Math.random() * 60000)
        clearNum = clearNum + Math.floor(Math.random() * 60000)
        clearNum = clearNum + 1000
        ekamtahark.innerText = `${Math.floor(val * (30 / 100))} Amd`
        soch.innerText = `${Math.floor(val * (10 / 100))} Amd`
        fe.innerText = `${Math.floor(val * (10 / 100))} Amd`
        tax.innerText = `${Math.floor(val * (13 / 100))} Amd`
        tax.innerText = `${Math.floor(val * (12 / 100))} Amd`
        Tax.innerText = `${Math.floor(val * (17 / 100))} Amd`
        vat.innerText = `${Math.floor(val * (15 / 100))} Amd`
        luys.innerText = Math.floor((Math.random() * 60000))
        jur.innerText = Math.floor(Math.random() *   60000)
        gas.innerText = Math.floor(Math.random() *   60000)
        inta.innerText = Math.floor(Math.random() *  60000)
        trash.innerText = Math.floor( Math.random()* 60000)
        phone.innerText = Math.floor( Math.random()* 60000)
        fee.innerText = Math.floor( Math.random()* 60000)
        cable.innerText = Math.floor( Math.random()* 60000)
        main.innerText = Math.floor( Math.random()* 60000)
        el.innerText = Math.floor( Math.random()* 60000)
        clear.innerText = val - clearNum
}else if(val <= 100000 && val >= 5000){
        clearNum = clearNum + Math.floor(val * 5 / 100)
        clearNum = clearNum + Math.floor(val * 1 / 100)
        clearNum = clearNum + Math.floor(val * 1 / 100)
        clearNum = clearNum + Math.floor(val * 4 / 100)
        clearNum = clearNum + Math.floor(val * 3 / 100)
        clearNum = clearNum + Math.floor(val * 5 / 100)
        clearNum = clearNum + Math.floor(val * 5 / 100)
        clearNum = clearNum + Math.floor(Math.random() * 20000 )
        clearNum = clearNum + Math.floor(Math.random() * 20000 )
        clearNum = clearNum + Math.floor(Math.random() * 20000 )
        clearNum = clearNum + Math.floor(Math.random() * 20000 )
        clearNum = clearNum + Math.floor(Math.random() * 20000 )
        clearNum = clearNum + Math.floor(Math.random() * 20000 )
        clearNum = clearNum + Math.floor(Math.random() * 20000 )
        clearNum = clearNum + Math.floor(Math.random() * 20000 )
        clearNum = clearNum + Math.floor(Math.random() * 20000 )
        clearNum = clearNum + Math.floor(Math.random() * 20000 )
        clearNum = clearNum + 1000
        ekamtahark.innerText = `${Math.floor(val * (5 / 100))} Amd`
        soch.innerText = `${Math.floor(val * (1 / 100))} Amd`
        fe.innerText = `${Math.floor(val * (1 / 100))} Amd`
        tax.innerText = `${Math.floor(val * (4 / 100))} Amd`
        tax2.innerText = `${Math.floor(val * (3 / 100))} Amd`
        Tax.innerText = `${Math.floor(val * (5 / 100))} Amd`
        vat.innerText = `${Math.floor(val * (5 / 100))} Amd`
        luys.innerText = Math.floor((Math.random() * 20000))
        jur.innerText = Math.floor(Math.random() * 20000)
        gas.innerText = Math.floor(Math.random() * 20000)
        inta.innerText = Math.floor(Math.random()  * 20000)
        trash.innerText = Math.floor( Math.random() * 20000)
        phone.innerText = Math.floor( Math.random() * 20000)
        fee.innerText = Math.floor( Math.random() * 20000)
        cable.innerText = Math.floor( Math.random() * 20000)
        main.innerText = Math.floor( Math.random() * 20000)
        el.innerText = Math.floor( Math.random() * 20000)
        clear.innerText = val - clearNum
}})